dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh | bashdist: trusty
notifications:
  slack:
    secure: bXz5LWxibYAfsSvKgC0XAGGi14ONjZrbM+Uv7yu09tVqEctUegN2IPLj8SnjmjQv/yE0AMkdNLijH0yBI1OV/OOeFyXaw2UIvAZeoQu4HRQczdh6BuEhrn7IG5YMSdIiwydoGz15R3mkyESuiPf3+H4jfjt2dLeGeen4UvpbJepRul8uVqA3wZnP3jMKF1vujv/8lGBBHcYP4JvBYIWtP6bGFbU/9N5y1aSkBlP8xwsE+0C9qbd/2xB2jN0TD1Bcoc+h3DiMSAE6hkEy4YKGmKg1mu9CgBwc5w5OTXwS4+dQci4G7Ioe8yuyTp9BhQ4PgE4qg2XT4WKbzn9FckEnfu83LTpKO29k7cvuyqSa3NrB80Nv/EQURUGTjF8E5d7WgRRaeP/gkWyBNvUSkGNp/gp2UopwAyOZGJwr2c3Uc+u2D+d4aWAfl6VWeYYRla6F+NjDutl7LS5cJKO+uQblEwChgtGq2Pv3v5Ch8MwCzEVhMhRViyTg9uiTZ8dhWztVHtOFrghecm4d3aGPIv0lF2mcZHCdG9ce4nxnZ3K+/5lVvan+ytDt+bZpH3oonnLEY3h73CbLPMlzdM6KXrDcGUkYcAt1a51QjYlVIUePVinPaQojW5rc8red5Iy3ilIv/jmGV7kX+IsnCwuB20eAqwXyPNN8n+QKCNdAThSaixQ=

