- name: Deploy App
  hosts: app
  become: true
  vars:
    deploy_user: ubuntu

  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/{{ deploy_user }}/reddit
        version: monolith
      notify: restart puma

    - name: bundle install
      bundler:
        state: present
        chdir: /home/{{ deploy_user }}/reddit
      notify: restart puma

  handlers:
  - name: restart puma
    ansible.builtin.shell: systemctl daemon-reload && systemctl restart puma
