---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone repo
  git:
    repo: https://github.com/express42/reddit.git
    dest: /home/ubuntu/reddit

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/ubuntu/db_config
    owner: ubuntu
    group: ubuntu

- name: Add unit file for Puma
  copy:
    src:  puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: enable puma
  ansible.builtin.shell: systemctl enable puma

