---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Install mongo
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
    - name: restart mongod
      ansible.builtin.shell: systemctl restart mongod && systemctl enable mongod

- name: Configure app
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.130.0.23
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: Add unit file for Puma
      copy:
        src:  files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: enable puma
      ansible.builtin.shell: systemctl enable puma

  handlers:
    - name: reload puma
      ansible.builtin.shell: systemctl daemon-reload && systemctl reload puma

- name: Deploy App
  hosts: app
  become: true
  tags: deploy-tag
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: restart puma

    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      notify: restart puma

  handlers:
  - name: restart puma
    ansible.builtin.shell: systemctl daemon-reload && systemctl restart puma
