---
dependency:
  name: galaxy
driver:
  name: vagrant
privider:
  name: virtualbox
platforms:
  - name: instance
    box: ubuntu/xenial64
provisioner:
  name: ansible
verifier:
  name: testinfra
  directory: ./tests
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8